import os
import logging
import uuid
import subprocess
import socket
import tempfile
import signal
import time
import threading
import select
import errno

from os.path import join as pathjoin

import psutil

from django.http import FileResponse, Http404
from django.urls import reverse

from api.views import ObjectManagerViewSet, ObjectManager
from api.serializers import StreamSerializer
from main import util


LOGGER = logging.getLogger(__name__)
LOGGER.setLevel(logging.DEBUG)
LOGGER.addHandler(logging.NullHandler())

WRITER_PROCESS_NAMES = ['ffmpeg']
STREAMS = ObjectManager()


def find_free_port(interface='localhost'):
    '''
    Finds a free port on given interface.

    Useful if you need to spawn ffmpeg as a server.
    '''
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    s.bind((interface, 0))
    try:
        return s.getsockname()[1]

    finally:
        s.close()


def _find_writers(path):
    '''
    Return pids of processes writing to given path. Only considers processes
    whose name is contained within WRITER_PROCESS_NAMES. Such filtering is an
    optimization as scanning all open files for all processes takes a
    considerable amount of time.
    '''
    pids = []

    for p in psutil.process_iter(attrs=['name']):
        # As of now, the only process that should be writing our video is
        # ffmpeg.
        if p.info['name'] not in WRITER_PROCESS_NAMES:
            continue

        try:
            files = p.open_files()

        except (psutil.NoSuchProcess, psutil.AccessDenied):
            # Process may have just died...
            continue

        else:
            # See if the ffmpeg process is writing to our video.
            for file in files:
                if file.path == path and 'w' in file.mode:
                    pids.append(p.pid)

    return pids


def _alive(pids):
    '''
    Return True if any of the given pids are alive.
    '''
    return any([p for p in pids if psutil.pid_exists(p)])


def _tails(process, paths):
    '''
    Read each path in turn and write it to the given process.

    Don't stop reading a file until no new data has arrived for 5s and no
    writing processes are detected. This allows us to stream a video from disk
    that is being generated by another process.

    Conceptually, this is like using tail -f on an apache log file, and when
    apache closes it's log, tail exits. Piping this tail-alike's output to
    another process, would cause THAT process to also die when apache closes
    it's log.

    Close the process.stdin when done. Typically this will cause the process to
    exit due to EOF.
    '''
    for path in paths:
        # Find processes currently writing to the file.
        pids = _find_writers(path)
        LOGGER.debug(
            'Found %i writers for path "%s": %s', len(pids), path,
            ",".join([str(p) for p in pids]))

        where, last_data = 0, time.time()
        input = open(path, 'rb')

        try:
            while True:
                # See if our streams are ready for I/O...
                input_readable = where < os.fstat(input.fileno()).st_size
                output_writable = \
                    select.select([], [process.stdin], [], 1.0)[1]

                if input_readable and output_writable:
                    data = input.read()
                    if data:
                        where, last_data = input.tell(), time.time()
                        process.stdin.write(data)

                    elif not pids and not input_readable:
                        # No writers, EOF
                        break

                else:
                    time.sleep(1.0)

                # If all of our writer pids have died, and we have not seen
                # data for 15s, move to next file.
                if not _alive(pids) and last_data < time.time() - 5:
                    break

        finally:
            input.close()

    # As desired, ffmpeg dies when we do this...
    process.stdin.close()
    process.wait()
    LOGGER.info('Input EOF, _tail() exiting.')


def _tail_to_ffmpeg(paths, command):
    '''
    Spawn a command and send a number of files to it's stdin.
    '''
    LOGGER.info(
        'Piping %i files to: "%s"', len(paths), " ".join(command))

    process = subprocess.Popen(
        command, stdin=subprocess.PIPE, shell=False)

    t_tail = threading.Thread(target=_tails, args=(process, paths))
    t_tail.daemon = True
    t_tail.start()

    return process


class Stream(object):
    def __init__(self, show=None):
        self.id = uuid.uuid4()
        self.show = show
        self.procress = None
        self.url = reverse('streams-playlist', args=[self.id])
        self.tempdir = None
        self.path = None
        self.start()

    def _create_tempdir(self):
        self.tempdir = tempfile.TemporaryDirectory(
            prefix='stream-%s' % self.id)
        self.path = self.tempdir.name

    def start(self):
        '''
        Information of using ffmpeg as an HTTP server:

        https://ffmpeg.org/ffmpeg-protocols.html#http
        '''
        self._create_tempdir()

        # Record to HLS format:
        playlist = pathjoin(self.path, 'stream.m3u8')
        file_names = util.get_recordings(self.show.path)

        # TODO: we need to detect the existing format and decide whether to
        # transcode or copy.
        command = [
            'ffmpeg', '-loglevel', 'fatal', '-i', 'pipe:0', '-c:v', 'h264',
            '-c:a', 'copy', '-flags', '+cgop', '-g', '30', '-hls_list_size',
            '0', '-hls_time', '3', playlist,
        ]

        # The video file could be written to, use tail to follow the file.
        self.process = _tail_to_ffmpeg(file_names, command)

    def stop(self):
        if self.process.poll() is None:
            self.process.send_signal(signal.SIGINT)
        self.tempdir.cleanup()


class StreamViewSet(ObjectManagerViewSet):
    serializer_class = StreamSerializer
    object_manager = STREAMS


def playlist(request, id):
    # TODO: we may wish to generate or modify this playlist. Although leaving
    # it alone may allow the player to rewind etc. The playlist controls the
    # options available to the user.
    try:
        stream = STREAMS[str(id)]

    except KeyError:
        raise Http404()

    playlist_path = pathjoin(stream.path, 'stream.m3u8')

    try:
        playlist_file = open(playlist_path, 'rb')

    except IOError as e:
        if e.errno != errno.ENOENT:
            raise
        raise Http404()

    return FileResponse(playlist_file)


def segment(request, id, name):
    # TODO: we can use the requested segment and UserAgent to store a cursor
    # for later resuming of playback
    try:
        stream = STREAMS[str(id)]

    except KeyError:
        raise Http404()

    segment_path = pathjoin(stream.path, '%s.ts' % name)

    try:
        segment_file = open(segment_path, 'rb')

    except IOError as e:
        if e.errno != errno.ENOENT:
            raise
        raise Http404()

    return FileResponse(segment_file)
