# Generated by Django 2.1.7 on 2019-02-16 02:43

import api.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
            bases=(api.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('poster', models.URLField(max_length=256, null=True)),
                ('year', models.SmallIntegerField()),
                ('desc', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(api.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('poster', models.URLField(max_length=256, null=True)),
                ('desc', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(api.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
            bases=(api.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=8)),
                ('stream', models.CharField(max_length=256, null=True)),
                ('poster', models.URLField(max_length=256, null=True)),
                ('hd', models.BooleanField(default=False)),
            ],
            bases=(api.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_agent', models.TextField(unique=True)),
                ('last_ip_address', models.GenericIPAddressField(null=True)),
                ('device_brand', models.CharField(max_length=32, null=True)),
                ('device_family', models.CharField(max_length=32, null=True)),
                ('device_model', models.CharField(max_length=32, null=True)),
                ('os_family', models.CharField(max_length=32, null=True)),
                ('os_major', models.CharField(max_length=32, null=True)),
                ('os_minor', models.CharField(max_length=32, null=True)),
                ('os_patch', models.CharField(max_length=32, null=True)),
                ('os_patch_minor', models.CharField(max_length=32, null=True)),
                ('user_agent_family', models.CharField(max_length=32, null=True)),
                ('user_agent_major', models.CharField(max_length=32, null=True)),
                ('user_agent_minor', models.CharField(max_length=32, null=True)),
                ('user_agent_patch', models.CharField(max_length=32, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(api.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('season', models.IntegerField()),
                ('episode_system', models.CharField(max_length=32)),
                ('episode', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
            bases=(api.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.SmallIntegerField(choices=[(0, 'movies'), (1, 'shows'), (2, 'music')])),
                ('name', models.CharField(max_length=32, unique=True)),
                ('path', api.models.DirectoryPathField(auto_create=True, max_length=256, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(api.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.SmallIntegerField(choices=[(0, 'Movie'), (1, 'Music'), (2, 'Show')])),
                ('path', api.models.FilePathField(auto_create_parent=True, max_length=256, must_exist=False, relative_to='library.path')),
                ('title', models.CharField(max_length=256)),
                ('subtitle', models.CharField(max_length=256)),
                ('desc', models.TextField()),
                ('poster', models.URLField(max_length=256, null=True)),
                ('has_metadata', models.BooleanField(default=False)),
                ('duration', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ('size', models.IntegerField(null=True)),
                ('format', models.CharField(max_length=32, null=True)),
                ('audio_enc', models.CharField(max_length=32, null=True)),
                ('play_count', models.IntegerField(default=0)),
                ('year', models.SmallIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(api.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('subtitle', models.CharField(max_length=256)),
                ('desc', models.TextField()),
                ('start', models.DateTimeField()),
                ('stop', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('poster', models.URLField(max_length=256, null=True)),
                ('previously_shown', models.BooleanField(default=True)),
                ('actors', models.ManyToManyField(to='api.Actor')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='api.Category')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='api.Channel')),
                ('episode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='api.Episode')),
            ],
            bases=(api.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
            bases=(api.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('stop', models.DateTimeField()),
                ('status', models.SmallIntegerField(choices=[(0, 'none'), (1, 'recording'), (2, 'error'), (3, 'done')], default=0)),
                ('pid', models.IntegerField(null=True)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='api.Program')),
            ],
            options={
                'abstract': False,
            },
            bases=(api.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(api.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
            bases=(api.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.SmallIntegerField(choices=[(0, 'hls'), (1, 'raw')])),
                ('path', api.models.DirectoryPathField(max_length=256, null=True)),
                ('pid', models.IntegerField(null=True)),
                ('cursor', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
            bases=(api.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Tuner',
            fields=[
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('ipaddr', models.GenericIPAddressField()),
                ('model', models.CharField(max_length=48)),
                ('tuner_count', models.SmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=(api.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Media')),
                ('width', models.SmallIntegerField(null=True)),
                ('height', models.SmallIntegerField(null=True)),
                ('video_enc', models.CharField(max_length=32, null=True)),
                ('actors', models.ManyToManyField(to='api.Actor')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.media',),
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Media')),
                ('track', models.SmallIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('api.media',),
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Media')),
                ('width', models.SmallIntegerField(null=True)),
                ('height', models.SmallIntegerField(null=True)),
                ('video_enc', models.CharField(max_length=32, null=True)),
                ('actors', models.ManyToManyField(to='api.Actor')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.media',),
        ),
        migrations.AddField(
            model_name='stream',
            name='media',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stream', to='api.Media'),
        ),
        migrations.AddField(
            model_name='program',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Rating'),
        ),
        migrations.AddField(
            model_name='media',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='api.Category'),
        ),
        migrations.AddField(
            model_name='media',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api.Library'),
        ),
        migrations.AddField(
            model_name='media',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Rating'),
        ),
        migrations.AddField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='api.Series'),
        ),
        migrations.AddField(
            model_name='channel',
            name='tuner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='api.Tuner'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='api.Artist'),
        ),
        migrations.AddField(
            model_name='show',
            name='episode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='api.Episode'),
        ),
        migrations.AddField(
            model_name='show',
            name='program',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shows', to='api.Program'),
        ),
        migrations.AddField(
            model_name='recording',
            name='show',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='api.Show'),
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('channel', 'start'), ('channel', 'stop')},
        ),
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='api.Album'),
        ),
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='api.Artist'),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('tuner', 'number')},
        ),
    ]
