# Generated by Django 2.1.7 on 2019-02-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190214_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='icon',
            new_name='poster',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='icon',
            new_name='poster',
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='icon',
            new_name='poster',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='icon',
            new_name='poster',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='icon',
            new_name='poster',
        ),
        migrations.AlterField(
            model_name='stream',
            name='cursor',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=12),
        ),
    ]
