# Generated by Django 2.1.7 on 2019-02-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190215_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='audio_enc',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='duration',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='format',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='has_metadata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='media',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='subtitle',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='height',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_enc',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='width',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='height',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='video_enc',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='width',
            field=models.SmallIntegerField(null=True),
        ),
    ]
