# Generated by Django 2.1.7 on 2019-02-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190215_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='length',
        ),
    ]
